image: docker:stable

stages:
  - build
  - deploy

before_script:
- docker info

build:
  stage: build
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/sedlak477/sirbotalot:latest .
  - docker push registry.gitlab.com/sedlak477/sirbotalot:latest
